apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: hello-idp
    newName: us-central1-docker.pkg.dev/PROJECT_ID/idp-artifacts/hello-idp
    newTag: prod
