apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: hello-idp
  newName: us-central1-docker.pkg.dev/internal-dev-platform/idp-artifacts/hello-idp
  newTag: 636569c0e1d3522229da2cde78887d91a3d4f514
