apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-idp-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/smithddevon/idp-gitops.git
    targetRevision: main
    path: apps/hello-idp/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
