apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-idp
spec:
  replicas:  1
  selector:
    matchLabels:
      app: hello-idp
  template:
    metadata:
      labels:
        app: hello-idp 
    spec:
      containers:
        - name: hello-idp
          image: hello-idp
          ports:
            - containerPort: 8080
